name: vi_auth_client
description: A client for connecting to ViAuth (auth.minoch.com)
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin
version: 0.0.9
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  http: ^0.11.3+14